version: '2'
services:
  database:
    container_name: daf.db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - api
  sprintboot:
    container_name: daf.api
    depends_on:
      - database
    links:
      - database
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
        - ./:/var/www/html
    entrypoint: |
      bash -c 'bash -s <<EOF
      cd /var/www/html && mvn spring-boot:run
      EOF'
    networks:
      - api

networks:
  api:
    driver: bridge
